### ISSUE TITLE
How to plot Annotation without using Ipython Notebook

### ISSUE THREAD

**Issue by jonlu0602** [pyannote/pyannote-core#17]
#### Description
I tried to use matplotlib to plot some figures from pyannote-metrics, and I faced some problems

#### Steps/Code to Reproduce
This is the code I tried, but it didn't work.

import numpy 
import matplotlib.pyplot as plt
from pyannote.core import Segment, Timeline, Annotation

plt.width = 10
plt.rcParams['figure.figsize'] = (plt.width, 3)
plt.crop = Segment(0, 40)
plt.subplot(211)

reference = Annotation()
reference[Segment(0, 10)] = 'A'
reference[Segment(12, 20)] = 'B'
reference[Segment(24, 27)] = 'A'
reference[Segment(30, 40)] = 'C'
pdb.set_trace()
**# plt.plot cannot take the reference.**
plt.gca().text(0.6, 0.15, 'reference', fontsize=16)
plt.show()

#### Expected Results
I hoped I can get the same figure in 
https://github.com/pyannote/pyannote-metrics/blob/master/notebooks/pyannote.metrics.diarization.ipynb

#### Versions
python 3.5

**Comment by hbredin** [comment]
```python
# initialize matplotlib
import matplotlib
matplotlib.use('Agg')
from matplotlib import pyplot as pet

# create the Annotation instance
from pyannote.core import Annotation, Segment
annotation = Annotation()
annotation[Segment(2, 5)] = 'A'
annotation[Segment(4, 8)] = 'B'
annotation[Segment(9, 10)] = 'A'

# choose to only plot [0, 10] timerange
# (defaults to the support of the first plotted annotation)
from pyannote.core import notebook
notebook.crop = Segment(0, 10)

# plot
figure, ax = plt.subplots()
notebook.plot_annotation(annotation, ax=ax, time=True, legend=True)

# save to file
figure.savefig('annotation.png')
```

`annotation.png` will look like this:

![annotation](https://user-images.githubusercontent.com/1080837/32003554-bb1f5830-b99f-11e7-9880-eb5efcaeac25.png)

**Comment by balazsgonczy** [comment]
Hi,

I am amused by your work. I would like to apply your "voice-activity-detection" class in order to extract speech from wav files. I am stucked because I don't know how to convert "pyannote.core.annotation.Annotation" type to array or something where I can exclude the non-speech related parts. May you give me some hint?
