### ISSUE TITLE
import pyannote.core fails

### ISSUE THREAD

**Issue by viannecc** [pyannote/pyannote-core#24]
I found when import a module that contains commands "from pyannote.core import Segment, Annotation" in a python module, it reports error: ‘ImportError: No module named 'pyannote.core'

My solution is change the import order. But Pycharm offers automatic import reorder, if using this, it reports the error.

Could u plz solve it ?

**Comment by hbredin** [comment]
Thanks for your interest in `pyannote.core`.

Can you please provide a detailed guide on a how to reproduce this error? 
It most likely results from an error occurring during installation.

**Comment by viannecc** [comment]
Sorry for replying late. I will represent more details as soon as possible since my code contains lots of  self-defined modules.

**Comment by viannecc** [comment]
The issue has been solved now. I'm going to close the issue.

**Comment by hammadfaheem** [comment]
try this 
import numpy as np

np.sctypes = {
    "int":   [np.int8, np.int16, np.int32, np.int64],
    "uint":  [np.uint8, np.uint16, np.uint32, np.uint64],
    "float": [np.float16, np.float32, np.float64],
    "complex": [np.complex64, np.complex128],
}
