### ISSUE TITLE
No module named 'pyannote.core'

### ISSUE THREAD

**Issue by viannecc** [pyannote/pyannote-core#27]
![WeChatWorkScreenshot_e3bc6947-63f8-43ea-96df-60cc7eb495ca](https://user-images.githubusercontent.com/13347286/60075101-20d09400-9757-11e9-9c5a-c1e5dadc1d35.png)

**Comment by viannecc** [comment]
Could you please help me fix the bug shown as picture above?

**Comment by hbredin** [comment]
Looks like you already solved this issue in https://github.com/pyannote/pyannote-core/issues/24

**Comment by viannecc** [comment]
I solved this at that time. But it comes out again...

**Comment by viannecc** [comment]
There are more details below:
**jieba** is a Chinese text segmentation python package.
I did some tests with commands shown in above picture:
jieba-0.39 pyannote-core-2.0.3  No bug
jieba-0.39 pyannote-core-2.1      No bug
jieba-0.39 pyannote-core-2.2.2  Bug occurs

So, I infer there is a conflict between v2.2.2 pyannote.core and jieba-0.39.

**Comment by hbredin** [comment]
Does this happen when you install `pyannote.core` in a fresh conda environment?
Can you please try with `pyannote.core 3.0` that I just released?

**Comment by hbredin** [comment]
Closing stalled issue. Please re-open if needed.

**Comment by Yagna24** [comment]
Hi, I have come across the same issue 

```
Using cache found in /root/.cache/torch/hub/pyannote_pyannote-audio_master

---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-20-4b7e923f233b> in <module>()
      1 import torch
----> 2 torch.hub.list('pyannote/pyannote-audio')

7 frames

/root/.cache/torch/hub/pyannote_pyannote-audio_master/pyannote/audio/features/utils.py in <module>()
     34 from librosa.util.exceptions import ParameterError
     35 
---> 36 from pyannote.core import SlidingWindow, SlidingWindowFeature
     37 
     38 from soundfile import SoundFile

ModuleNotFoundError: No module named 'pyannote.core'


while running this : 

```
import torch 
torch.hub.list('pyannote/pyannote-audio') 

```


```

**Comment by pooya-mohammadi** [comment]
@Yagna24 
Did you have any chance on solving the issue?

**Comment by pooya-mohammadi** [comment]
```
!pip install -U pyannote.audio==1.1
!pip install pyannote.core
```
Solved it for now!

**Comment by Yagna24** [comment]
@pooya-mohammadi   I have ran the pip install commands but I still get the same error
` ModuleNotFoundError: No module named 'pyannote.core'`

I am running this on colab...

**Comment by pooya-mohammadi** [comment]
@Yagna24 
make sure to restart your session after installing the executing the following cell on google colab:
```
!pip install -U pyannote.audio==1.1
!pip install pyannote.core
```

**Comment by Yagna24** [comment]
> @Yagna24 make sure to restart your session after installing the executing the following cell on google colab:
> 
> ```
> !pip install -U pyannote.audio==1.1
> !pip install pyannote.core
> ```

Yes, always restarting the runtime after install helps

**Comment by Ibn-mohey** [comment]
> 

it doent do any thing the same probems appears
