### ISSUE TITLE
Annotation.crop() and .copy() weird behavior

### ISSUE THREAD

**Issue by DonkeyShot21** [pyannote/pyannote-core#28]
Hi, thanks for the awesome tool!

I am trying to make some cool visualizations of my model on tensorboard. I need to crop my Annotations because the audio files that I am using are too long to be visualized correctly. I decided to use the `.crop()` function you provide to do that. This is the code:

    def build_annotation(sequence, meta):
        annotation = Annotation(uri=meta[0][0])
        for segment, m in zip(sequence, meta):
            start, end = float(m[-2]), float(m[-2]) + float(m[-1])
            annotation[Segment(start, end)] = segment
        return annotation

    def draw_annotations(hp, ref, collar=0.0):
        fig, (ax1, ax2) = plt.subplots(2, 1)
        notebook.plot_annotation(hp.support(collar=collar), ax=ax1, legend=False)
        notebook.plot_annotation(ref.support(collar=collar), ax=ax2, legend=False)
        ax1.autoscale()
        ax2.autoscale()
        fig.tight_layout()
        fig.set_dpi(180)
        fig.canvas.draw()
        img = np.array(fig.canvas.renderer.buffer_rgba()).astype(np.float32)
        img = np.transpose(img,(2,0,1))/np.amax(img)
        return img

    def visual_annotations(pred, gt, pred_meta, gt_meta, max_len=30):
        plots = {}
        hp_annotation = [build_annotation(s, m) for s, m in zip(pred, pred_meta)]
        ref_annotation = [build_annotation(s, m) for s, m in zip(gt, gt_meta)]
        for hp, ref, gt_m in zip(hp_annotation, ref_annotation, gt_meta):
            end = math.ceil(max(hp.get_timeline().duration(),
                                ref.get_timeline().duration()))
            for x in range(0, end, max_len):
                print('/'.join([gt_m[0][0], str(x//max_len)]))
                sub_hp = hp.copy().crop(Segment(x, x + max_len))
                sub_ref = ref.copy().crop(Segment(x, x + max_len))
                img = draw_annotations(sub_hp, sub_ref)
                plots['/'.join([gt_m[0][0], str(x//max_len)])] = img
        return plots

Note that in `visual_annotations` I use `.copy()` in order to preserve the original annotation for the next iteration.

This is the result:
![Screenshot from 2019-08-22 20-49-34](https://user-images.githubusercontent.com/19649581/63541466-71c5f400-c51e-11e9-93fb-e8b2a4265fdd.png)

As you can see just the first subannotation gets rendered correctly, the others are completely blank. It is also weird because it looks like the time does not go forward (the support is always the same).
I checked and the segments show up when I print the subannotations after cropping, so the data seems to be there. Is it just a problem with the support? I tried passing a cropped `Timeline` instead of a `Segment` but the result is the same.

I tried with different solutions but I cannot get it to work. Is there something very obvious I cannot see?

**Comment by hbredin** [comment]
Try calling `notebook.reset()` in the inner `for` loop. 

I answer from my phone so cannot afford to give more insight right now but my answer to this issue might give you an explanation as to why this works:
https://github.com/pyannote/pyannote-core/issues/23#issuecomment-495211651

**Comment by DonkeyShot21** [comment]
Thanks a lot, it worked like a charm!
