### ISSUE TITLE
Unclear or wrong docstring in Annotation.crop

### ISSUE THREAD

**Issue by PaulLerner** [pyannote/pyannote-core#32]
Hi,

Isn't there a mistake in [Annotation.crop](https://github.com/pyannote/pyannote-core/blob/develop/pyannote/core/annotation.py#L351) ? 
You say that "If `support` is a `Timeline`, its support is used." but isn't it the other way around ?
Because [you turn support into Timeline if it's a Segment](https://github.com/pyannote/pyannote-core/blob/develop/pyannote/core/annotation.py#L380)

Bests,

**Comment by hbredin** [comment]
Looking at the code, it looks like the `docstring` is indeed wrong and does not describe what is really happening. Thanks for catching this!

However, this has nothing to do with the fact that `Segment` instances are first turned into `Timeline`.  A picture is worth a thousand words:

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/1080837/70307197-e9d3d380-1808-11ea-8944-43837861b5f9.png">

I am not quite sure what to do with this. 
We would need to find all places where `Annotation.crop` has been used in the pyannote ecosystem and, then only, decide if we just fix the docstring to match code behavior or vice-versa.

**Comment by hbredin** [comment]
Fixed in dd41c92. Updated behavior of Annotation.crop and Timeline.crop to match their docstring.
