### ISSUE TITLE
TypeError: __bool__ should return bool, returned numpy.bool_ when running the intro tutorial

### ISSUE THREAD

**Issue by jsanc525** [pyannote/pyannote-core#38]
Hello,
Apologies in advance if there is something super obvious I'm missing.

when running this line of code from the documentation tutorial:
partition = peak.apply(scd_scores, dimension=1)

i get the following error:
TypeError: __bool__ should return bool, returned numpy.bool_

I followed the install instructions to the letter with the exception that I used conda activate vs. source activate when activating the conda environment. I have also tried running the code python 3.6 and 3.7, and tried my best to trace what was happening in the background, but I wasn't able to find what i need to change.

Thanks in advance for any advice

**Comment by hbredin** [comment]
This is fixed in `pyannote.core` 3.2.2.
