### ISSUE TITLE
Is there a way to reset the beginning time after annotation.crop() to 0?

### ISSUE THREAD

**Issue by terrykwon** [pyannote/pyannote-core#43]
```python
crop = annotation.crop(Segment(60, 120))
```

The above returns an annotation with nothing in time [0, 60], then the cropped segments in the interval [60, 120] (which is obviously intended behavior).

Is there a way to "shift" the crop so that the segments begin at time 0?

**Comment by hbredin** [comment]
There is no such thing in the API. Something like this might work, though:

```python
from pyannote.core import Segment, Annotation
crop = annotation.crop(Segment(60, 120))

shifted_crop = Annotation(uri=crop.uri)
for segment, track, label in crop.itertracks(yield_label=True):
    shifted_segment = Segment(segment.start - 60, segment.end - 60)
    shifted_crop[shifted_segment, track] = label
```

**Comment by terrykwon** [comment]
Worked perfectly! Thanks a lot.
