### ISSUE TITLE
Controlling time span in notebook visualization

### ISSUE THREAD

**Issue by nellorebhanuteja** [pyannote/pyannote-core#51]
If we type 
`reference`
this generates a plot of reference in notebook.

However, the x range seems to be fixed in [0, 40]

Is there a way to change this x range?

**Comment by hbredin** [comment]
`pyannote.core` will automatically use the time span of the first annotation it displays.

* If you want to reset the time span, use:
```python
from pyannote.core import notebook
notebook.reset()
```

* If you want to use a specific time span, use:
```python
from pyannote.core import notebook, Segment
notebook.crop = Segment(0, 40)
```

I'd happily merge a pull request adding this to the documentation.
