### ISSUE TITLE
return list in annotation.get_labels

### ISSUE THREAD

**Issue by PaulLerner** [pyannote/pyannote-core#53]
Hi,
[`annotation.get_labels`](https://github.com/pyannote/pyannote-core/blob/develop/pyannote/core/annotation.py#L726) returns `dict_values` if `unique=False`.
Shouldn't it return a `list` since `dict_values` are not subscriptable ?

**Comment by hbredin** [comment]
It should indeed return a `list`. 

This is a reminiscence of Python 2.7 that used to return a `list` instead of a `dict_values`.

PR? :-)
