### ISSUE TITLE
Diarization Label Output Ordering

### ISSUE THREAD

**Issue by petersnias** [pyannote/pyannote-core#62]
After going through the diarization tutorial, I use the following script

fn = "example.wav"
out_rttm = "output.rttm"

torch.hub.load('pyannote/pyannote-audio', 'dia',device="cuda",batch_size=64)

diarization = pipeline({'audio': fn})

with open(out_rttm,"w") as f:
            diarization.write_rttm(f)

When I write to the out_rttm file, one expectation is for the 1st label to be associated with the 1st speaker (i.e. speaker 1 = A, speaker 2 = B, etc.).  Currently the 1st speaker can be any letter.

Is there a function I can call or parameter I can set to achieve the 1st label being associated with 1st speaker and so on in the output labels?  Thank you.

**Comment by hbredin** [comment]
Check out methods [`rename_labels`](http://pyannote.github.io/pyannote-core/reference.html?highlight=rename_labels#pyannote.core.Annotation.rename_labels) of `pyannote.core.Annotation`.

You'd have to build your own `mapping` dictionary and call `diarization.rename_labels(mapping=mapping)`.

**Comment by petersnias** [comment]
Hi Herve,

Thank you for the response.  This renames the labels which I was able to
accomplish.  The issue I am having is order.  For example for some of my
longer audio files, I get diarization Annotations such as:

st_1 et_1 F
st_2 et_2 F
st_3 et_3 H


Where I would expect the first speaker to come in as A, the 2nd as B, and
so on

st_1 et_1 A
st_2 et_2 A
st_3 et_3 B

The reason is, in our ground truth dataset, we always assume the labels
come in order so the first person to speak is speaker1 and the 2nd is
speaker 2, etc.   Is there a parameter I could pass to ensure this order is
maintained?  The interesting thing is, this isn't the case for shorter
audio (say < 5 min)...then the annotations are in order of speaker, but for
the longer audio, the order is random.

I assume that if this functionality isn't available, I would have to
dynamically do a renaming mapping for each audio file since I can't ensure
what labels map to the 1st, 2nd, etc speakers.  Is this accurate

Thank you in advance for any clarification you could provide.  If you need
additional clarification from my end, please let me know.

Cheers,
Nia
