### ISSUE TITLE
Issues using Annotation.support(collar)

### ISSUE THREAD

**Issue by petersnias** [pyannote/pyannote-core#67]
Hi,

I would like to take an original rttm file and merge the tracks across contiguous labels and write the annotation back to another rttm file.  I've attached the original rttm (1_original.rttm) and merge contiguous labels file (1_contLabel.rttm) a reference to where I have observed the two issues below:

Here is my code:
file = '1_orginal.rttm'
out_file = '1_contLabel.rttm'
groundtruth = load_rttm(file)['1']
groundtruth = groundtruth.support(collar=1)
with open(out_file, 'w') as f:
        groundtruth.write_rttm(f)

Issues 1: the duration changes for some non-contiguous labels

In 1_orignal.rttm the annotation is:
SPEAKER 1 1 48.954 **1.8230000000000004** <NA> <NA> sp2 <NA>

In 1_contLabel.rttm the annotation changes to:
SPEAKER 1 1 48.954 **3.882** <NA> <NA> sp2 <NA> <NA>

Is there another parameter I need to set in support() to prevent this from happening?

Issues 2:  Overlaps removed

In the original rttm if the chunks are overlapping, they are just taken out when support is used.  Is there a way I can maintain these labels?  

In 1_orignal.rttm the annotation is:
SPEAKER 1 1 50.641 0.3760000000000048 <NA> <NA> sp1 <NA>
SPEAKER 1 1 50.785 2.051000000000002 <NA> <NA> sp2 <NA>

In 1_contLabel.rttm the annotation changes to:

Thank you in advance for your help

[pyannote_metrics_nsp.zip](https://github.com/pyannote/pyannote-audio/files/7323554/pyannote_metrics_nsp.zip)

**Comment by hbredin** [comment]
> Here is my code: file = '1_orginal.rttm' out_file = '1_contLabel.rttm' groundtruth = load_rttm(file)['1'] groundtruth = groundtruth.support(collar=1) with open(out_file, 'w') as f: groundtruth.write_rttm(f)
> 
> Issues 1: the duration changes for some non-contiguous labels
> 
> In 1_orignal.rttm the annotation is: SPEAKER 1 1 48.954 **1.8230000000000004** sp2
> 
> In 1_contLabel.rttm the annotation changes to: SPEAKER 1 1 48.954 **3.882** sp2
> 
> Is there another parameter I need to set in support() to prevent this from happening?

This is the expected behavior: see [documentation](http://pyannote.github.io/pyannote-core/reference.html#pyannote.core.Annotation.support) of `collar` argument.

**Comment by hbredin** [comment]
<img width="722" alt="image" src="https://user-images.githubusercontent.com/1080837/136940329-65cb8d90-2bb9-4dad-b929-8fafdb1c1ce8.png">

**Comment by petersnias** [comment]
So just to clarify.  If the original is

st dur label:
0 1 spk1
1.5 3.0 spk1
4 5 spk 2
6 2 spk 1

and I set collar to 1 after support is would be

0 4.5 spk1
4 5 spk2
6 2 spk1

Is this correct?

The problem I'm having is, I get something like
0 4.5 spk1
4 *6 *spk2
6 2 spk1

Why is the duration for spk2 changing? I thought collar would only affect
spk1 since the time between 1 sec and 1.5 is < 1 sec but do you mind
explaining what affect this would have on spk2? I reread the documentation
and this wasn't as clear.

Thank you so much in advance for the help.

**Comment by hbredin** [comment]
Closing stale issue. Please re-open if needed.
